Fix an AttributeError in shutdown().
When the collector was already dead, calling shutdown() would cause:
  File "/usr/local/tcollector/tcollector.py", line 130, in shutdown
      if self.proc.exitstatus() is None:
  AttributeError: 'NoneType' object has no attribute 'exitstatus'
This could happen if the collector had died and was then removed from
the filesystem for instance.

Change-Id: I2a766adfae9f65048a5182aca5dc1ce71c31c48e
Reviewed-on: https://review.stumble.net/647
Reviewed-by: Benoit Sigoure <tsuna@stumbleupon.com>
Tested-by: Benoit Sigoure <tsuna@stumbleupon.com>