Fix for procnettcp.py if IPv6 is disabled
If /proc/net/tcp6 doesn't exist, we die with:
procnettcp.py:     procfile.seek(0)
AttributeError: 'NoneType' object has no attribute 'seek'

Change-Id: I9127be78df8cf497cc8cbc25a857d5552bc03012
Reviewed-on: https://review.stumble.net/1952
Tested-by: Benoit Sigoure <tsuna@stumbleupon.com>
Reviewed-by: Benoit Sigoure <tsuna@stumbleupon.com>