fix shebang line to find the first python on PATH
If /usr/bin/python comes with the OS, it could be wildly out-of-date,
causing strange errors like:

    Traceback (most recent call last):
      File "collectors/0/hbase_regionserver.py", line 24, in ?
        from collectors.lib.hadoop_http import HadoopHttp
      File "collectors/lib/hadoop_http.py", line 47
        finally:
              ^
    SyntaxError: invalid syntax

Even if tcollector.py is started with a modern Python.

Fixing the #! lines to use /usr/bin/env ensures that the first python on the
PATH is used.